releases:
- name: elastalert
  version: latest

networks: (( merge ))

jobs:
- name: elastalert
  templates:
  - name: elastalert
    release: elastalert
  instances: 1
  resource_pool: small_z1
  persistent_disk: 10400
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
